name: Test

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  tests:
    uses: ./.github/workflows/_tests.yml
  console-tests:
    uses: ./.github/workflows/_tests_console.yml
  tests-pc:
    uses: ./.github/workflows/_tests_pc.yml
